import io
from fpdf import FPDF


class StartupPDF(FPDF):
    def __init__(self, title: str):
        super().__init__()
        self.doc_title = title
        self.set_margins(20, 20, 20)
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(37, 99, 235)  # blue
        self.cell(0, 8, self.doc_title, align="L")
        self.set_text_color(180, 180, 180)
        self.cell(0, 8, "Generated by StartupGPT", align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(220, 220, 220)
        self.line(20, self.get_y(), 190, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")

    def add_section_header(self, text: str):
        self.ln(4)
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(37, 99, 235)
        self.cell(0, 8, text, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(37, 99, 235)
        self.line(20, self.get_y(), 80, self.get_y())
        self.ln(3)

    def add_body_text(self, text: str):
        self.set_font("Helvetica", "", 11)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 6, text)
        self.ln(2)


def text_to_pdf(content: str, title: str) -> bytes:
    """
    Convert plain text with --- section headers into a formatted PDF.
    Returns PDF as bytes.
    """
    pdf = StartupPDF(title)
    pdf.add_page()

    # Split content into sections by --- dividers
    sections = content.split("---")

    for section in sections:
        section = section.strip()
        if not section:
            continue

        lines = section.split("\n")
        header = lines[0].strip()
        body = "\n".join(lines[1:]).strip()

        if header:
            pdf.add_section_header(header)
        if body:
            pdf.add_body_text(body)

    return bytes(pdf.output())